site_name: Panhans | Blueprints and Snippets
site_url: https://panhans.github.io/HomeAssistant/

nav:
  - 🏠 Home: "index.md"
  - 🔥 Advanced Heating Control:
    - 📖 Sections & Inputs:
      - 🔘 Thermostats & Sensors: "ahc/sections/thermostats_sensors.md"
      - 🌡️ Temperatures: "ahc/sections/temperatures.md"
      - 🎛️ Adjustements & Heating Plan: "ahc/sections/adjustments_heating_plan.md"
      - 🤜 Force Comfort/Eco Mode: "ahc/sections/force_comfort_eco.md"
      - 🎚️ Temperature Tweaks: "ahc/sections/temperature_tweaks.md"
      - 👥 Persons: "ahc/sections/persons.md"
      - 🕑 Scheduling: "ahc/sections/schedules.md"
      - 🚶 Presence Detection: "ahc/sections/presence_detection.md"
      - ↔️ Proximity: "ahc/sections/proximity.md"
      - 🏃 Away Mode: "ahc/sections/away_mode.md"
      - 🪟 Windows & Doors: "ahc/sections/windows_doors.md"
      - 🧭 Calibration: "ahc/sections/calibration.md"
      - 😡 Aggressive Mode: "ahc/sections/aggressive_mode.md"
      - ⌖ Dynamic Valve Positioning: "ahc/sections/dynamic_valve_positioning.md"
    - 👆 Hints:
      - 🔑 Keywords: "ahc/hints/keywords.md"

docs_dir: docs_src
edit_uri: edit/main/src/
site_dir: docs

extra_css:
  - style.css

theme:
  name: "material"
  language: "en"
  font: false
  # logo: "assets/logos/website_logo.png"
  # favicon: "assets/logos/favicon/favicon-32x32.png"
  # custom_dir: "docs/assets/overrides"
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: "white"
      toggle:
        icon: "material/weather-night"
        name: "Dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: "slate"
      toggle:
        icon: "material/weather-sunny"
        name: "Light mode"
  features:
    - "navigation.instant"
    - "navigation.tracking"
    - "navigation.top"
    - "navigation.tabs"
    - "navigation.indexes"
    - "search.suggest"
    - "search.highlight"
    - "search.share"
    - "content.code.annotate"
    - "content.tabs.link"

markdown_extensions:
  - "meta"
  - "pymdownx.superfences"
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - "admonition"
  - "pymdownx.details"
  - "pymdownx.inlinehilite"
  # - pymdownx.snippets:
  #    base_path: [".", "custom_components/ui_lovelace_minimalist"]
  #    check_paths: true
  - "pymdownx.critic"
  - "pymdownx.caret"
  - "pymdownx.keys"
  - "pymdownx.tilde"
  - pymdownx.blocks.caption
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: "Panhans"
      repo: "HomeAssistant"
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - "tables"
  - "footnotes"
  - "attr_list"
  - "md_in_html"
  - "def_list"
  - toc:
      permalink: true

plugins:
  - "search"
  - "awesome-pages"
  - "glightbox"